import { ARTISTS } from "../src/data/artists.js";

const queries = [
  ["法老", "法老"],
  ["马思唯", "马思唯"],
  ["姜云升", "姜云升"],
  ["Jony J", "Jony J"],
  ["TizzyT", "Tizzy"],
  ["乃万", "乃万", "NINEONE"],
  ["小鬼王琳凯", "小鬼", "Lil Ghost", "王琳凯", "Ghost"],
  ["沙一汀", "沙一汀", "EL"],
  ["Capper", "Capper"],
  ["杨和苏", "杨和苏", "KeyNG"],
  ["GAI", "GAI"],
  ["王以太", "王以太"],
  ["KEY.L刘聪", "刘聪", "KEY.L"],
  ["加木", "加木"],
  ["万妮达", "万妮达", "Vinida"],
  ["Ice Paper", "Ice Paper"],
  ["贝贝李京泽", "贝贝", "李京泽", "ljz329"],
  ["派克特", "派克特", "PACT"],
  ["罗言", "罗言"],
  ["黄旭", "黄旭", "BooM"],
  ["Asen", "Asen", "艾志恒"],
  ["GALI", "GALI"],
  ["Spylent", "Spylent"],
  ["KnowKnow", "KnowKnow"],
  ["热狗", "热狗", "HotDog"],
  ["幼稚园杀手", "幼稚园杀手"],
  ["宝石Gem", "宝石", "Gem"],
  ["Rapeter", "Rapeter"],
  ["欧阳靖", "欧阳靖", "MC Jin"],
  ["盛宇", "盛宇", "D-SHINE"],
  ["满舒克", "满舒克"],
  ["PSY.P", "PSY.P"],
  ["Melo", "Melo", "墨龙"],
  ["胡天渝", "胡天渝", "福克斯", "FOX"],
  ["kkluv", "kkluv"],
  ["那奇沃夫", "那奇沃夫"],
  ["Top Barry", "Top Barry"],
  ["连麻", "连麻", "Swimming"],
  ["thomeboydontkill", "THOME", "thomeboy"],
  ["Sasi", "Sasi", "SASIOVER"],
  ["mac ova seas", "mac ova seas"],
  ["BigYear大年", "BigYear", "大年"],
  ["李佳隆", "李佳隆"],
  ["邓典果", "邓典果", "DDG"],
  ["艾热", "艾热"],
  ["艾福杰尼", "艾福杰尼"],
  ["布瑞吉", "布瑞吉", "Bridge"],
  ["功夫胖", "功夫胖"],
  ["弹壳", "弹壳", "Danko"],
  ["丁飞", "丁飞", "HipHopMan"],
  ["刘柏辛", "刘柏辛", "Lexie"],
  ["王澳楠", "王澳楠", "EVE"],
  ["张方钊", "张方钊"],
  ["蛋堡", "蛋堡", "Soft Lipa"],
  ["瘦子E.SO", "瘦子", "E.SO"],
  ["愚月", "愚月", "FoolMoon"],
  ["于意", "于意", "Yee"],
  ["AY杨佬叁", "杨佬叁", "楊佬叁", "AY"],
  ["李尔新", "李尔新"],
  ["刘思鉴", "刘思鉴"],
  ["Lil Jet", "Lil Jet", "陆政廷"],
  ["孟子坤", "孟子坤"],
  ["廖效浓", "廖效浓"],
  ["高天佐", "高天佐", "Trouble.Z"],
  ["贰万", "贰万"],
  ["早安", "早安"],
  ["西奥Sio", "西奥", "Sio"],
  ["Subs张毅成", "Subs", "张毅成"],
  ["圣代", "圣代"],
  ["江奈生", "江奈生"],
  ["夏之禹", "夏之禹"],
  ["Bsh-1", "Bsh-1", "Bsh"],
  ["Ash-1", "Ash-1", "Ash"],
  ["极品贵公子", "极品贵公子"],
  ["kKECHO", "kKECHO", "陈欣瑶"],
  ["AA", "AA"],
  ["等一下就回家", "等一下就回家"],
  ["木秦", "木秦"],
  ["Gm仙", "Gm仙", "Gm 仙"],
  ["孤影杀手", "孤影杀手"],
  ["K.ila", "K.ila"],
  ["生番刘悦", "生番", "spam", "刘悦"],
  ["鱼翅Fin", "鱼翅", "Fin"],
  ["小安迪", "小安迪", "LilAndy"],
  ["直火帮Feezy", "Feezy"],
  ["直火帮XZT", "XZT"],
  ["Zinco", "Zinco", "泥鳅"],
  ["王齐铭", "王齐铭", "WatchMe"],
  ["小青龙", "小青龙"],
  ["鬼卞", "鬼卞"],
  ["3Bangz", "3Bangz"],
  ["未来星", "未来星", "B3Rich"],
  ["徐真真", "徐真真"],
  ["河南说唱之神", "河南说唱之神"],
  ["河北Ye", "河北 Ye", "河北Ye"],
  ["杀手耗", "杀手耗"],
  ["辉子", "辉子"],
  ["黄礼格", "黄礼格"],
  ["永彬Ryan.B", "永彬", "Ryan.B"],
  ["梁老师", "梁老师", "Tsong", "梁淞"],
  ["高尔宣", "高尔宣", "OSN"],
  ["熊仔", "熊仔"],
  ["陈娴静", "陈娴静", "陳嫺靜", "嫺靜"],
  ["Majin", "Majin"],
  ["God Øne", "God Øne", "God One", "GodØne"],
  ["国蛋", "国蛋", "GorDoN"],
  ["小春Kenzy", "小春", "Kenzy"],
  ["大渊Muta", "大渊", "Muta"],
  ["新秀", "新秀"],
  ["莫梭", "莫梭"],
  ["SASIOVERLXRD", "SASIOVERLXRD"],
  ["CashTrippy", "CashTrippy"],
  ["阿茹汗", "阿茹汗"],
  ["巴音汗", "巴音汗"],
  ["八贼Buzzy", "Buzzy", "八贼"],
  ["曲甲", "曲甲", "大表哥"],
  ["秃子2z", "秃子", "2z"],
];

function match(alts) {
  return ARTISTS.find((a) => {
    const n = a.name.toLowerCase();
    return alts.some((q) => n.includes(String(q).toLowerCase()));
  });
}

const missing = [];
const present = [];
for (const [label, ...alts] of queries) {
  const hit = match([label, ...alts]);
  if (hit) present.push({ label, name: hit.name, fans: hit.fans });
  else missing.push({ label, search: [label, ...alts] });
}

console.log(JSON.stringify({ totalRoster: ARTISTS.length, present: present.length, missing: missing.length, missing }, null, 2));
